frontend:
  root:
    url: http://localhost:4200/
logging:
  level:
    org:
      hibernate:
        SQL: debug
spring:
  datasource:
    driver-class-name: org.postgresql.Driver

    url: jdbc:postgresql://localhost:5432/Db_Booking
    password: 123456
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 5050
